---
- name: Fetch PHPStan latest release version.
  uri:
    url: https://api.github.com/repos/phpstan/phpstan/releases/latest
    body_format: json
    return_content: true
  register: json_response

- name: Install PHPStan.
  become: true
  get_url:
    url: https://github.com/phpstan/phpstan/releases/download/{{ json_response.json.tag_name }}/phpstan.phar
    dest: /usr/local/bin/phpstan
    mode: 0755
    force: true
